config/routes.rb
Rails.application.routes.draw do
  resources :job_applications
  root to: 'home#index'
  get 'home/index', as: :home

  devise_for :users
  resources :users
  resources :jobs do
    member do
      post :apply
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employer, class_name: 'User'
  has_many :job_applications
  has_many :applicants, through: :job_applications, source: :user, foreign_key: :user_id
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :user, uniqueness: { scope: :job,
    message: "can apply only one time" }

  enum status: { accepted: 0, rejected: 1, hold: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs, foreign_key: :employer_id

  has_many :job_applications
  has_many :applied_jobs, through: :job_applications, source: :job, foreign_key: :job_id
  enum role: { employer: 0, applicant: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name role])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, only: %i[ show edit update destroy ]

  # GET /job_applications or /job_applications.json
  def index
    @job_applications = JobApplication.all
  end

  # GET /job_applications/1 or /job_applications/1.json
  def show
  end

  # GET /job_applications/1/edit
  def edit
  end

  # POST /job_applications or /job_applications.json
  def create
    @job_application = JobApplication.new(job_application_params)

    respond_to do |format|
      if @job_application.save
        format.html { redirect_to job_application_url(@job_application), notice: "Job application was successfully created." }
        format.json { render :show, status: :created, location: @job_application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_applications/1 or /job_applications/1.json
  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html { redirect_to job_application_url(@job_application), notice: "Job application was successfully updated." }
        format.json { render :show, status: :ok, location: @job_application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applications/1 or /job_applications/1.json
  def destroy
    @job_application.destroy

    respond_to do |format|
      format.html { redirect_to job_applications_url, notice: "Job application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_application
      @job_application = JobApplication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_application_params
      params.fetch(:job_application, {})
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy apply]

  def index
    @jobs = current_user.jobs if current_user.employer?
    @jobs ||= Job.all
  end

  def show
  end

  def new
    @job = current_user.jobs.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def apply
    # TODO: show user friendly error notice
    respond_to do |format|
      if @job.applicants << current_user
        format.html { redirect_to job_url(@job), notice: "Applied for job successfully." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.fetch(:job, {}).
      permit(:title, :vacancy, :experience, :salary).
      merge({ employer_id: current_user.id })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.joins(job_applications: :job).select('users.*, job_applications.status as application_status, jobs.title as job_title').where('job_applications.job_id': current_user.jobs.ids)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb

app/views/job_applications/_form.html.haml
= form_for @job_application do |f|
  - if @job_application.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job_application.errors.count, "error")} prohibited this job_application from being saved:"
      %ul
        - @job_application.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/job_applications/_job_application.html.haml
%table.table
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Applicant name 
      %th{:scope => "col"} Job title
      %th{:scope => "col"} Status
  %tbody
    %tr
      %td
      %td= "#{job_application.user.first_name} #{job_application.user.last_name}"
      %td= job_application.job.title
      %td= job_application.status
      %td= link_to 'Show', job_application
      %td= link_to 'Edit', edit_job_application_path(job_application)
      %td= link_to 'Destroy', job_application, method: :delete, data: { confirm: 'Are you sure?' }

app/views/job_applications/edit.html.haml
%h1 Editing job_application

= render 'form'

= link_to 'Show', @job_application
\|
= link_to 'Back', job_applications_path

app/views/job_applications/index.html.haml
%h1 Job Applications
#job_application
  - @job_applications.each do |job_application|
    = render job_application
%br

app/views/job_applications/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_job_application_path(@job_application)
\|
= link_to 'Back', job_applications_path

app/views/jobs/_form.html.haml
= form_with(model: job) do |f|
  - if job.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(job.errors.count, "error")
        prohibited this job from being saved:
      %ul
        - job.errors.each do |error|
          %li= error.full_message
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control", placeholder: "Enter Job title"
  -# TODO: add description column
  .form-group
    = f.label :vacancy
    = f.number_field :vacancy, class: "form-control", placeholder: "Number of vacancies"
  .form-group
    = f.label :experience
    = f.number_field :experience, class: "form-control", placeholder: "Experience required in years"
  .form-group
    = f.label :salary
    = f.number_field :salary, class: "form-control", placeholder: "Salary"
  %div
    = f.submit

app/views/jobs/_job.html.haml
%div{:id => "#{dom_id job}"}
%table.table
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Title 
      %th{:scope => "col"} Vacancy
      %th{:scope => "col"} Employer
      %th{:scope => "col"} Experience
      %th{:scope => "col"} Salary

  %tbody
    %tr
      %th{:scope => "row"}
      %td 
        = job.title
      %td
        = job.vacancy
      %td
        = "#{job.employer.first_name} #{job.employer.last_name}"
      %td
        = job.experience
      %td
        = job.salary

app/views/jobs/edit.html.haml
%h1 Editing job
= render "form", job: @job
%br/
%div
  = link_to "Show this job", @job
  |
  \#{link_to "Back to jobs", jobs_path}

app/views/jobs/index.html.haml
%p{:style => "color: green"}= notice
%h1 Jobs
#jobs
  - @jobs.each do |job|
    = render job
    %p
      = link_to "Show this job", job, class: 'btn btn-primary'
= link_to "New job", new_job_path

app/views/jobs/new.html.haml
%h1 New job
= render "form", job: @job
%br/
%div
  = link_to "Back to jobs", jobs_path

app/views/jobs/show.html.haml
%p{:style => "color: green"}= notice
= render @job
%div
  = link_to 'Apply', apply_job_path, data: { "turbo-method": :post }, class: 'btn btn-success' if current_user.applicant?

  = link_to "Edit this job", edit_job_path(@job) if current_user.employer?
  |
  \#{link_to "Back to jobs", jobs_path}
  
  \#{button_to "Destroy this job", @job, method: :delete, class: 'btn btn-danger' if current_user.employer?}

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.bg-light
  .container-fluid
    %a.navbar-brand{:href => home_url} LinkedIn
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => jobs_url} Jobs
        - if current_user && current_user.employer?
          %li.nav-item
            %a.nav-link{:href => users_path} Applicants
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
      %form.d-flex
        %a.nav-link.disabled
          - if user_signed_in?
            = link_to 'signout', destroy_user_session_path, data: { "turbo-method": :delete }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LinkedinLite
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    = render 'layouts/header'
    .container
      .alert
        - if notice
          %p.notice.alert-primary= notice
        - if alert
          %p.alert.alert-danger= alert
      = yield

app/views/users/_form.html.haml
= form_with(model: user) do |form|
  - if user.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.each do |error|
          %li= error.full_message
  %div
    = form.submit

app/views/users/_user.html.haml
%table.table
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} First Name
      %th{:scope => "col"} Last Name
      %th{:scope => "col"} Email
      %th{:scope => "col"} Role
      %th{:scope => "col"} Applied for
      %th{:scope => "col"} Status
  %tbody
    %tr
      %th{:scope => "row"}
      %td= user.first_name
      %td= user.last_name
      %td= user.email
      %td= user.role
      %td= user.job_title
      %td= select_tag 'Application status', options_for_select(JobApplication.statuses.keys.map { |key| [key.humanize, key] }), selected: user.application_status, include_blank: true, id: "#{dom_id user}" 

app/views/users/edit.html.haml
%h1 Editing user
= render "form", user: @user
%br/
%div
  = link_to "Show this user", @user
  |
  \#{link_to "Back to users", users_path}

app/views/users/index.html.haml
%p{:style => "color: green"}= notice
%h1 Applicants
#applicants
  - @users.each do |user|
    = render user
    %p
= link_to "New user", new_user_path

app/views/users/new.html.haml
%h1 New user
= render "form", user: @user
%br/
%div
  = link_to "Back to users", users_path